# Generated by Django 4.1.2 on 2023-01-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laundry_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
